up:
	goose postgres "host=localhost user=postgres database=rss_bot password=postgres sslmode=disable" up

down:
	goose postgres "host=localhost user=postgres database=rss_bot password=postgres sslmode=disable" down